### ISSUE TITLE
Fix sidebar wrapping

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2.github.io#15]
![image](https://cloud.githubusercontent.com/assets/274668/19205600/5a84343a-8c98-11e6-947d-867ca09feb46.png)

Maybe just one line per entry? Right aligned.

**Comment by jakereps** [comment]
Some of the headings are just too long, so using single lines they'll stick way off the page, would just adding some padding between them help clear up which are which?

**Comment by thermokarst** [comment]
How about we just drop the `div.sphinxsidebar` rules in the ~~CSS~~ custom CSS? It diverges from the qiime style, though. Thoughts?

![screen shot 2016-10-10 at 2 23 41 pm](https://cloud.githubusercontent.com/assets/274668/19251641/2eae728a-8ef5-11e6-990f-523505f626c6.png)
