### ISSUE TITLE
pseudo-RFC: Centralize a q2stylesheet?

### ISSUE THREAD

**Issue by jakereps** [qiime2/qiime2.github.io#38]
**Improvement Description**
The base stylesheet should be standardized, and each one that requires modifications (docs specifically) should probably be split into (as a docs example) `_static/custom.css`, which will control the admonitions and any other custom/site-specific tweaks that are now intertwined in the main theme stylesheet.

**Current Behavior**
Currently the same stylesheet is being spread across multiple repositories and projects. There is one in workshops, docs source, every docs version build, the root for the docs build, and this repo. 

**Proposed Behavior**
This could be accomplished by only having one central main sheet on this repo that the other "pieces" use to build around with their custom tweaks. So, again for docs, the theme would just have a link to the url for this main repo, instead of having a hardcoded sheet in its source.

This could also be utilized to have a single source of `bootstrap.min.css` and `normalize.css` as there is a copy in every docs build, and the docs root as well.

**Questions**
Thoughts?

**Comment by jairideout** [comment]
@thermokarst suggested that q2templates might be a good home for this, maybe hosting built css on a branch -- thoughts?

**Comment by jakereps** [comment]
That definitely sounds good to me! So just a `gh-pages` branch off of `q2templates`?

**Comment by lizgehret** [comment]
We're going to fully re-do the website, so this no longer applies. Closing.
